name: IQDent

color:
    primary: 2C3E50
    secondary: 18BC9C
    
contact:
    office:
        fb: http://facebook.com/IQDent
        gplus: https://plus.google.com/b/112364347924666080247
        twitter: 
        tel: 
            
    one: 
        name: Dr. Irina Alexandru
        tel: 0766 748 971
        img: img/team/1.jpg
        fb:
    two: 
        name: Dr. Bogdan Calenic
        tel: 0755 044 047
        img: img/team/2.jpg
        fb:
